//
// Created by korycki on 30.03.2023.
//

#ifndef SORTING_ALGORITHMS_STATISTICCOLLECTOR_H
#define SORTING_ALGORITHMS_STATISTICCOLLECTOR_H





#endif //SORTING_ALGORITHMS_STATISTICCOLLECTOR_H
